cat Toc.md \
00-Introduction.md \
breakline.txt \
01-Block-Bindings.md \
breakline.txt \
02-Strings-and-Regular-Expressions.md \
breakline.txt \
03-Functions.md \
breakline.txt \
04-Objects.md \
breakline.txt \
05-Destructuring.md \
breakline.txt \
06-Symbols.md \
breakline.txt \
07-Sets-And-Maps.md \
breakline.txt \
08-Iterators-And-Generators.md \
breakline.txt \
09-Classes.md \
breakline.txt \
10-Arrays.md \
breakline.txt \
11-Promises.md \
breakline.txt \
12-Proxies-and-Reflection.md \
breakline.txt \
13-Modules.md \
breakline.txt \
A-Other-Changes.md \
breakline.txt \
B-ECMAScript-7.md \
> Book.md
